# Generated by Django 5.1.2 on 2025-03-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto_perfil', models.TextField(default='https://img.freepik.com/premium-vector/man-avatar-drawing_65141-572.jpg')),
            ],
        ),
    ]
